sudo: required

env:
  - DOCKER_COMPOSE_VERSION=1.19.0

before_install:
  # Upgrade docker-compose to appropriate version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  # Set env vars
  - cp .env.sample .env
  - sed -i 's/MIX_ENV=dev/MIX_ENV=test/' .env
  - sed -i 's/POSTGRES_PASSWORD=/POSTGRES_PASSWORD=travis/' .env

install:
  - docker-compose build
  - docker-compose run --rm web mix do deps.get, compile

script:
  - docker-compose up -d
  - docker-compose exec -T web mix do ecto.create, ecto.migrate, test
