version: '3.3'
services:
  db:
    image: mdillon/postgis:10
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  web:
    build:
      context: ./language_map
    ports:
      - "${WEB_APP_PORT}:4000"
    command: mix phx.server
    env_file:
      - .env
    environment:
      - MIX_ENV=${MIX_ENV}
      - PORT=${WEB_APP_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
    volumes:
      - ./language_map:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/_build
      - /usr/src/app/deps
      - /usr/src/app/priv/static
    links:
      - db
