version: '3.3'
services:
  db:
    image: pcaisse/language-map-us:db-${DB_VERSION}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  web:
    image: pcaisse/language-map-us:web-${WEB_VERSION}
    ports:
      - "${WEB_APP_PORT}:8080"
    command: mix run --no-halt
    env_file:
      - .env
    environment:
      - MIX_ENV=${MIX_ENV}
      - PORT=${WEB_APP_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
    links:
      - db
