version: '3.3'
services:
  db:
    build:
      context: ./postgres
    env_file:
      - .env
    environment:
      # Env vars for image
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # Env vars for PostgreSQL
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
      - PGHOST=db
    volumes:
      - ./postgres/data/:/usr/src/data/
      - ./postgres/scripts/:/usr/src/scripts/
      - pums:/usr/src/pums/
      - puma:/usr/src/puma/

  web:
    build:
      context: ./language_map
    ports:
      - "${WEB_APP_PORT}:8080"
    command: mix run --no-halt
    env_file:
      - .env
    environment:
      - MIX_ENV=${MIX_ENV}
      - PORT=${WEB_APP_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
    volumes:
      - ./language_map/:/usr/src/app/
    links:
      - db

volumes:
  pums:
  puma:
