version: '3.3'
services:
  db:
    image: mdillon/postgis:10
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/usr/src/data

  web:
    build:
      context: ./language_map
    ports:
      - "${WEB_APP_PORT}:8080"
    command: mix run --no-halt
    env_file:
      - .env
    environment:
      - MIX_ENV=${MIX_ENV}
      - PORT=${WEB_APP_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
    volumes:
      - ./language_map/lib:/usr/src/app/lib
      - ./language_map/config:/usr/src/app/config
      - ./language_map/priv:/usr/src/app/priv
      - ./language_map/mix.exs:/usr/src/app/mix.exs
    links:
      - db
