name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./data
          push: true
          tags: pcaisse/language-map-data:latest
          cache-from: type=registry,ref=pcaisse/language-map-data:latest
          cache-to: type=inline

      - name: Build vector tiles
        run: docker run --volume=$(pwd)/data/scripts:/usr/src/app --volume=$(pwd)/app/test/data:/usr/src/data --volume=$(pwd)/app/static/tiles:/tiles pcaisse/language-map-data bash -c "./process_files --pums /usr/src/data/pums --geom /usr/src/data/shapefiles --output /tiles --year 2019 --state 72"

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.1.0
        env:
          BASEMAP_STYLE: http://localhost:3000/test/style.json
          TILES_URL: http://localhost:3000/tiles/{z}/{x}/{y}.pbf
        with:
          build: npm run build
          start: npm start
          working-directory: app
